insert into neighborhood values("CONCORDIA");
insert into neighborhood values("OVERLOOK");
insert into neighborhood values("ARBOR LODGE");
insert into neighborhood values("RICHMOND");
insert into neighborhood values("HOSFORD-ABERNETHY");
insert into neighborhood values("KENTON");
insert into neighborhood values("MONTAVILLA");
insert into neighborhood values("PARKROSE HEIGHTS");
insert into neighborhood values("UNIVERSITY PARK");
insert into neighborhood values("SELLWOOD-MORELAND");
insert into neighborhood values("WOODLAND PARK");
insert into neighborhood values("BUCKMAN");
insert into neighborhood values("HAZELWOOD");
insert into neighborhood values("PORTSMOUTH");
insert into neighborhood values("SUNNYSIDE");
insert into neighborhood values("CENTENNIAL");
insert into neighborhood values("MILL PARK");
insert into neighborhood values("EASTMORELAND");
insert into neighborhood values("BROOKLYN");
insert into neighborhood values("CRESTON-KENILWORTH");
insert into neighborhood values("WOODSTOCK");
insert into neighborhood values("FOSTER-POWELL");
insert into neighborhood values("MT. SCOTT-ARLETA");
insert into neighborhood values("ARDENWALD-JOHNSON CREEK");
insert into neighborhood values("LENTS");
insert into neighborhood values("BRENTWOOD-DARLINGTON");
insert into neighborhood values("REED");
insert into neighborhood values("ROSEWAY");
insert into neighborhood values("ROSE CITY PARK");
insert into neighborhood values("CULLY");
insert into neighborhood values("MADISON SOUTH");
insert into neighborhood values("PDX");
insert into neighborhood values("SUMNER");
insert into neighborhood values("PEARL");
insert into neighborhood values("PARKROSE");
insert into neighborhood values("RUSSELL");
insert into neighborhood values("DOWNTOWN");
insert into neighborhood values("NORTHWEST DISTRICT");
insert into neighborhood values("ARGAY");
insert into neighborhood values("WILKES");
insert into neighborhood values("GLENFAIR");
insert into neighborhood values("ST. JOHNS");
insert into neighborhood values("CATHEDRAL PARK");
insert into neighborhood values("SOUTH PORTLAND");
insert into neighborhood values("OLD TOWN/ CHINATOWN");
insert into neighborhood values("GOOSE HOLLOW");
insert into neighborhood values("SOUTHWEST HILLS");
insert into neighborhood values("GRANT PARK");
insert into neighborhood values("KERNS");
insert into neighborhood values("LAURELHURST");
insert into neighborhood values("IRVINGTON");
insert into neighborhood values("SULLIVAN'S GULCH");
insert into neighborhood values("LLOYD DISTRICT");
insert into neighborhood values("NORTH TABOR");
insert into neighborhood values("ELIOT");
insert into neighborhood values("BEAUMONT-WILSHIRE");
insert into neighborhood values("HOLLYWOOD");
insert into neighborhood values("BOISE");
insert into neighborhood values("ALAMEDA");
insert into neighborhood values("WOODLAWN");
insert into neighborhood values("HAYDEN ISLAND");
insert into neighborhood values("BRIDGETON");
insert into neighborhood values("PIEDMONT");
insert into neighborhood values("HUMBOLDT");
insert into neighborhood values("EAST COLUMBIA");
insert into neighborhood values("SOUTH TABOR");
insert into neighborhood values("VERNON");
insert into neighborhood values("SABIN");
insert into neighborhood values("KING");
insert into neighborhood values("MT. TABOR");
insert into neighborhood values("SUNDERLAND");
insert into neighborhood values("HILLSIDE");
insert into neighborhood values("ARLINGTON HEIGHTS");
insert into neighborhood values("POWELLHURST-GILBERT");
insert into neighborhood values("PLEASANT VALLEY");
insert into neighborhood values("NORTHWEST INDUSTRIAL");
insert into neighborhood values("FOREST PARK");
insert into neighborhood values("NORTHWEST HEIGHTS");
insert into neighborhood values("WEST PORTLAND PARK");
insert into neighborhood values("MARSHALL PARK");
insert into neighborhood values("MARKHAM");
insert into neighborhood values("FAR SOUTHWEST");
insert into neighborhood values("LINNTON");
insert into neighborhood values("HOMESTEAD");
insert into neighborhood values("HILLSDALE");
insert into neighborhood values("CRESTWOOD");
insert into neighborhood values("MAPLEWOOD");
insert into neighborhood values("SYLVAN HIGHLANDS");
insert into neighborhood values("HAYHURST");
insert into neighborhood values("MULTNOMAH");
insert into neighborhood values("BRIDLEMILE");
insert into neighborhood values("COLLINS VIEW");
insert into neighborhood values("ASH CREEK");
insert into neighborhood values("SOUTH BURLINGAME");
insert into neighborhood values("ARNOLD CREEK");
