insert into tree_details_species values("Prunus serrulata - Japanese flowering cherry", "Broadleaf deciduous");
insert into tree_details_species values("Cornus spp. - dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Acer platanoides - Norway maple", "Broadleaf deciduous");
insert into tree_details_species values("Quercus bicolor - swamp white oak", "Broadleaf deciduous");
insert into tree_details_species values("Acer rubrum - red maple", "Broadleaf deciduous");
insert into tree_details_species values("Prunus cerasifera - flowering plum", "Broadleaf deciduous");
insert into tree_details_species values("Betula spp. - birch", "Broadleaf deciduous");
insert into tree_details_species values("Cornus kousa - kousa dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Malus domestica - apple (MADO)", "Broadleaf deciduous");
insert into tree_details_species values("Juglans spp. - walnut, butternut", "Broadleaf deciduous");
insert into tree_details_species values("Magnolia grandiflora - southern magnolia", "Broadleaf evergreen");
insert into tree_details_species values("Magnolia spp. - magnolia", "Broadleaf deciduous");
insert into tree_details_species values("Gleditsia spp. - honey locust", "Broadleaf deciduous");
insert into tree_details_species values("Acer pseudoplatanus - sycamore maple", "Broadleaf deciduous");
insert into tree_details_species values("Zelkova serrata - Japanese zelkova", "Broadleaf deciduous");
insert into tree_details_species values("Platanus x acerifolia - London plane tree", "Broadleaf deciduous");
insert into tree_details_species values("Cercidiphyllum japonicum - katsura", "Broadleaf deciduous");
insert into tree_details_species values("Prunus dulcis syn. Prunus amygdalus - almond", "Broadleaf deciduous");
insert into tree_details_species values("Juglans regia - English walnut", "Broadleaf deciduous");
insert into tree_details_species values("Cornus florida - eastern dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Pinus spp. - pine", "Coniferous evergreen");
insert into tree_details_species values("Acer griseum - paperbark maple", "Broadleaf deciduous");
insert into tree_details_species values("Acer x freemanii - red-silver maple hybrid", "Broadleaf deciduous");
insert into tree_details_species values("Tilia cordata - littleleaf linden", "Broadleaf deciduous");
insert into tree_details_species values("Prunus (plum species and cultivars) - plum", "Broadleaf deciduous");
insert into tree_details_species values("Quercus rubra - northern red oak", "Broadleaf deciduous");
insert into tree_details_species values("Fagus sylvatica - European beech", "Broadleaf deciduous");
insert into tree_details_species values("Trachycarpus fortunei - windmill palm", "Broadleaf evergreen");
insert into tree_details_species values("Clerodendrum spp. - glory bower", "Broadleaf deciduous");
insert into tree_details_species values("Picea spp. - spruce", "Coniferous evergreen");
insert into tree_details_species values("Quercus coccinea - scarlet oak", "Broadleaf deciduous");
insert into tree_details_species values("Cedrus spp. - cedar", "Coniferous evergreen");
insert into tree_details_species values("Parrotia persica - Persian ironwood", "Broadleaf deciduous");
insert into tree_details_species values("Fraxinus spp. - ash", "Broadleaf deciduous");
insert into tree_details_species values("Diospyros spp. - persimmon", "Broadleaf deciduous");
insert into tree_details_species values("Tilia spp. - linden or basswood", "Broadleaf deciduous");
insert into tree_details_species values("Cornus controversa - giant dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Thuja spp. - ", "Coniferous evergreen");
insert into tree_details_species values("Nyssa sylvatica - black tupelo", "Broadleaf deciduous");
insert into tree_details_species values("Cydonia oblonga - quince", "Broadleaf deciduous");
insert into tree_details_species values("Pyrus spp. - pear", "Broadleaf deciduous");
insert into tree_details_species values("Aesculus spp. - horsechestnuts, buckeyes", "Broadleaf deciduous");
insert into tree_details_species values("Sorbus spp. - mountain ash", "Broadleaf deciduous");
insert into tree_details_species values("Prunus (cherry species and cultivars) - cherry", "Broadleaf deciduous");
insert into tree_details_species values("Acer palmatum - Japanese maple", "Broadleaf deciduous");
insert into tree_details_species values("Prunus laurocerasus - English laurel", "Broadleaf evergreen");
insert into tree_details_species values("Crataegus monogyna - English hawthorn", "Broadleaf deciduous");
insert into tree_details_species values("Koelreuteria paniculata - goldenrain tree", "Broadleaf deciduous");
insert into tree_details_species values("Acer tataricum ssp. Ginnala - Amur maple", "Broadleaf deciduous");
insert into tree_details_species values("Styrax japonicus - Japanese snowbell", "Broadleaf deciduous");
insert into tree_details_species values("Malus spp. - ornamental crabapple", "Broadleaf deciduous");
insert into tree_details_species values("Ginkgo biloba - ginkgo", "Broadleaf deciduous");
insert into tree_details_species values("Lagerstroemia spp. - crape myrtle", "Broadleaf deciduous");
insert into tree_details_species values("Fraxinus ornus - flowering ash", "Broadleaf deciduous");
insert into tree_details_species values("Acer grandidentatum 'Schmidt' - Rocky Mountain Glow maple", "Broadleaf deciduous");
insert into tree_details_species values("Oxydendrum arboreum - sourwood", "Broadleaf deciduous");
insert into tree_details_species values("Cryptomeria japonica - Japanese cedar", "Coniferous evergreen");
insert into tree_details_species values("Quercus garryana - Oregon white oak", "Broadleaf deciduous");
insert into tree_details_species values("Carpinus spp. - hornbeam", "Broadleaf deciduous");
insert into tree_details_species values("xSycoparrotia semidecidua - sycoparrotia", "Broadleaf deciduous");
insert into tree_details_species values("Ulmus spp. - elm", "Broadleaf deciduous");
insert into tree_details_species values("Unknown", null);
insert into tree_details_species values("Acer saccharinum - silver maple", "Broadleaf deciduous");
insert into tree_details_species values("Cercis spp. - redbud", "Broadleaf deciduous");
insert into tree_details_species values("Acer circinatum - vine maple", "Broadleaf deciduous");
insert into tree_details_species values("Fraxinus angustifolia - narrowleaf ash", "Broadleaf deciduous");
insert into tree_details_species values("Juniperus spp. - juniper", "Coniferous evergreen");
insert into tree_details_species values("Quercus palustris - pin oak", "Broadleaf deciduous");
insert into tree_details_species values("Ulmus americana - American elm", "Broadleaf deciduous");
insert into tree_details_species values("Alnus spp. - alder", "Broadleaf deciduous");
insert into tree_details_species values("Tilia tomentosa - silver linden", "Broadleaf deciduous");
insert into tree_details_species values("Fagus spp. - beech", "Broadleaf deciduous");
insert into tree_details_species values("Ficus carica - common fig", "Broadleaf deciduous");
insert into tree_details_species values("Juglans nigra - black walnut", "Broadleaf deciduous");
insert into tree_details_species values("Acer campestre - hedge maple", "Broadleaf deciduous");
insert into tree_details_species values("Pseudotsuga menziesii - Douglas-fir", "Coniferous evergreen");
insert into tree_details_species values("Photinia serrulata - Chinese photinia", "Broadleaf evergreen");
insert into tree_details_species values("Fraxinus americana - white ash", "Broadleaf deciduous");
insert into tree_details_species values("Acer negundo - box elder", "Broadleaf deciduous");
insert into tree_details_species values("Acer saccharum - sugar maple", "Broadleaf deciduous");
insert into tree_details_species values("Syringa reticulata - Japanese tree lilac", "Broadleaf deciduous");
insert into tree_details_species values("Cornus mas - cornelian cherry dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Abies spp. - fir", "Coniferous evergreen");
insert into tree_details_species values("Carpinus japonica - Japanese hornbeam", "Broadleaf deciduous");
insert into tree_details_species values("Chionanthus retusus - Chinese fringe tree", "Broadleaf deciduous");
insert into tree_details_species values("Crataegus douglasii - black hawthorn", "Broadleaf deciduous");
insert into tree_details_species values("Ilex spp. - holly", "Broadleaf evergreen");
insert into tree_details_species values("Corylus spp. - hazel or hazelnut", "Broadleaf deciduous");
insert into tree_details_species values("Crataegus x lavalleei - Lavalle hawthorn", "Broadleaf deciduous");
insert into tree_details_species values("Fraxinus excelsior 'Aureafolia' - golden desert ash", "Broadleaf deciduous");
insert into tree_details_species values("Acer spp. - maple", "Broadleaf deciduous");
insert into tree_details_species values("Styrax obassia - fragrant snowbell", "Broadleaf deciduous");
insert into tree_details_species values("Cladrastis spp. - yellowwood", "Broadleaf deciduous");
insert into tree_details_species values("Maackia amurensis - Amur maackia", "Broadleaf deciduous");
insert into tree_details_species values("Carya illinoinensis - pecan", "Broadleaf deciduous");
insert into tree_details_species values("Betula nigra - river birch", "Broadleaf deciduous");
insert into tree_details_species values("Magnolia x soulangeana - saucer magnolia", "Broadleaf deciduous");
insert into tree_details_species values("Liriodendron tulipifera - tulip tree", "Broadleaf deciduous");
insert into tree_details_species values("Quercus hypoleucoides - silverleaf oak", "Broadleaf evergreen");
insert into tree_details_species values("Ulmus x - elm hybrid", "Broadleaf deciduous");
insert into tree_details_species values("Quercus suber - cork oak", "Broadleaf evergreen");
insert into tree_details_species values("Callitropsis nootkatensis - Nootka Cypress", "Coniferous evergreen");
insert into tree_details_species values("Hesperocyparis spp. - Western Cypress", "Coniferous evergreen");
insert into tree_details_species values("Stewartia spp. - stewartia", "Broadleaf deciduous");
insert into tree_details_species values("Salix spp. - willow", "Broadleaf deciduous");
insert into tree_details_species values("Laurus nobilis - bay laurel", "Broadleaf deciduous");
insert into tree_details_species values("Ostrya spp. - hophornbeam", "Broadleaf deciduous");
insert into tree_details_species values("Catalpa spp. - catalpa", "Broadleaf deciduous");
insert into tree_details_species values("Liquidambar styraciflua - sweetgum", "Broadleaf deciduous");
insert into tree_details_species values("Quercus spp. (evergreen) - evergreen oak", "Broadleaf evergreen");
insert into tree_details_species values("Chamaecyparis obtusa - Hinoki falsecypress", "Coniferous evergreen");
insert into tree_details_species values("Umbellularia californica - Oregon myrtle", "Broadleaf evergreen");
insert into tree_details_species values("Carpinus betulus - European hornbeam", "Broadleaf deciduous");
insert into tree_details_species values("Chamaecyparis spp. - falsecypress", "Coniferous evergreen");
insert into tree_details_species values("Rhamnus purshiana - cascara buckthorn", "Broadleaf deciduous");
insert into tree_details_species values("Cotinus spp. - smoketree", "Broadleaf deciduous");
insert into tree_details_species values("Cupressus spp. - cypress", "Coniferous evergreen");
insert into tree_details_species values("Gymnocladus dioica - Kentucky coffee tree", "Broadleaf deciduous");
insert into tree_details_species values("Populus tremuloides - quaking aspen", "Broadleaf deciduous");
insert into tree_details_species values("Carpinus caroliniana - American hornbeam", "Broadleaf deciduous");
insert into tree_details_species values("Acer macrophyllum - bigleaf maple", "Broadleaf deciduous");
insert into tree_details_species values("Albizia julibrissin - silk tree", "Broadleaf deciduous");
insert into tree_details_species values("Populus spp. - poplar", "Broadleaf deciduous");
insert into tree_details_species values("Magnolia virginiana - sweetbay", "Broadleaf evergreen");
insert into tree_details_species values("Eucalyptus spp. - eucalyptus", "Broadleaf evergreen");
insert into tree_details_species values("Amelanchier spp. - serviceberry", "Broadleaf deciduous");
insert into tree_details_species values("Acer buergerianum - trident maple", "Broadleaf deciduous");
insert into tree_details_species values("Prunus spp. - other", "Broadleaf deciduous");
insert into tree_details_species values("Crataegus spp. - hawthorn", "Broadleaf deciduous");
insert into tree_details_species values("Ailanthus altissima - tree of heaven", "Broadleaf deciduous");
insert into tree_details_species values("Arbutus unedo - strawberry tree", "Broadleaf evergreen");
insert into tree_details_species values("Pinus ponderosa - ponderosa pine", "Coniferous evergreen");
insert into tree_details_species values("Cornus nuttallii - Pacific dogwood", "Broadleaf deciduous");
insert into tree_details_species values("Arbutus spp. - strawberry tree or madrone", "Broadleaf evergreen");
insert into tree_details_species values("xChitalpa tashkentensis - chitalpa", "Broadleaf deciduous");
insert into tree_details_species values("Pistacia chinensis - Chinese pistache", "Broadleaf deciduous");
insert into tree_details_species values("Salix matsudana 'Tortuosa' - corkscrew willow", "Broadleaf deciduous");
insert into tree_details_species values("Calocedrus decurrens - incense cedar", "Coniferous evergreen");
insert into tree_details_species values("Fraxinus pennsylvanica - green ash", "Broadleaf deciduous");
insert into tree_details_species values("xCupressocyparis leylandii - Leyland cypress", "Coniferous evergreen");
insert into tree_details_species values("Fraxinus excelsior - European ash", "Broadleaf deciduous");
insert into tree_details_species values("Robinia pseudoacacia - black locust", "Broadleaf deciduous");
insert into tree_details_species values("Betula pendula - European white birch", "Broadleaf deciduous");
insert into tree_details_species values("Ligustrum spp. - privet", "Broadleaf evergreen");
insert into tree_details_species values("Quercus ilex - Holm oak or holly oak", "Broadleaf evergreen");
insert into tree_details_species values("Lithocarpus spp. - tanoak", "Broadleaf evergreen");
insert into tree_details_species values("Laburnum spp. - goldenchain tree", "Broadleaf deciduous");
insert into tree_details_species values("Ulmus pumila - Siberian elm", "Broadleaf deciduous");
insert into tree_details_species values("Prunus virginiana - chokecherry", "Broadleaf deciduous");
insert into tree_details_species values("Cedrus deodara - deodar cedar", "Coniferous evergreen");
insert into tree_details_species values("Olea europaea - olive", "Broadleaf evergreen");
insert into tree_details_species values("Crataegus phaenopyrum - Washington hawthorn", "Broadleaf deciduous");
insert into tree_details_species values("Prunus avium - bird cherry", "Broadleaf deciduous");
insert into tree_details_species values("Metasequoia glyptostroboides - dawn redwood", "Coniferous deciduous");
insert into tree_details_species values("Maclura pomifera - Osage orange", "Broadleaf deciduous");
insert into tree_details_species values("Castanea spp. - chestnut", "Broadleaf deciduous");
insert into tree_details_species values("Thuja plicata - western redcedar", "Coniferous evergreen");
insert into tree_details_species values("Pterostyrax spp. - epaulette tree", "Broadleaf deciduous");
insert into tree_details_species values("Sequoiadendron giganteum - giant sequoia", "Coniferous evergreen");
insert into tree_details_species values("Prunus persica - peach", "Broadleaf deciduous");
insert into tree_details_species values("Ulmus parvifolia - Chinese lacebark elm", "Broadleaf deciduous");
insert into tree_details_species values("Quercus robur - English oak", "Broadleaf deciduous");
insert into tree_details_species values("Azara microphylla - boxleaf azara", "Broadleaf evergreen");
insert into tree_details_species values("Acer capillipes - Japanese snakebark maple", "Broadleaf deciduous");
insert into tree_details_species values("Fraxinus latifolia - Oregon ash", "Broadleaf deciduous");
insert into tree_details_species values("Araucaria araucana - monkey puzzle", "Coniferous evergreen");
insert into tree_details_species values("Tilia americana - American linden", "Broadleaf deciduous");
insert into tree_details_species values("Euonymus spp. - euonymus", "Broadleaf deciduous");
insert into tree_details_species values("Sequoia sempervirens - coast redwood", "Coniferous evergreen");
insert into tree_details_species values("Arbutus menziesii - Pacific madrone", "Broadleaf evergreen");
insert into tree_details_species values("Pinus strobus - eastern white pine", "Coniferous evergreen");
insert into tree_details_species values("Prunus armeniaca - apricot", "Broadleaf deciduous");
insert into tree_details_species values("Chamaecyparis pisifera - sawara cypress", "Coniferous evergreen");
insert into tree_details_species values("Quercus spp. - oak", "Broadleaf deciduous");
insert into tree_details_species values("Pinus nigra - Austrian pine", "Coniferous evergreen");
insert into tree_details_species values("Citrus spp. - citrus", "Broadleaf evergreen");
insert into tree_details_species values("Larix spp. - larch", "Coniferous deciduous");
insert into tree_details_species values("Morus spp. - mulberry", "Broadleaf deciduous");
insert into tree_details_species values("Celtis spp. - hackberry", "Broadleaf deciduous");
insert into tree_details_species values("Pinus contorta var. contorta - shore pine", "Coniferous evergreen");
insert into tree_details_species values("Quercus acutissima - sawtooth oak", "Broadleaf deciduous");
insert into tree_details_species values("Prunus serrula - paperbark cherry", "Broadleaf deciduous");
insert into tree_details_species values("Tsuga spp. - hemlock", "Coniferous evergreen");
insert into tree_details_species values("Elaeagnus spp. - Russian-olive, silverberry, oleaster", "Broadleaf deciduous");
insert into tree_details_species values("Quercus × bimundorum - Two Worlds Oak", "Broadleaf deciduous");
insert into tree_details_species values("Eriobotrya spp. - loquat", "Broadleaf evergreen");
insert into tree_details_species values("Asimina triloba - paw paw", "Broadleaf deciduous");
insert into tree_details_species values("Ulmus propinqua 'JFS-Bieberich' - Emerald Sunshine elm", "Broadleaf deciduous");
insert into tree_details_species values("Phellodendron spp. - corktree", "Broadleaf deciduous");
insert into tree_details_species values("Eucommia ulmoides - Hardy rubber tree", "Broadleaf deciduous");
insert into tree_details_species values("Tilia platyphyllos - largeleaf linden", "Broadleaf deciduous");
insert into tree_details_species values("Pinus monticola - Western white pine", "Coniferous evergreen");
insert into tree_details_species values("Styphnolobium japonicum syn. Sophora japonica - Japanese pagoda tree", "Broadleaf deciduous");
insert into tree_details_species values("Quercus phellos - willow oak", "Broadleaf deciduous");
insert into tree_details_species values("Paulownia tomentosa - paulownia, Empress tree", "Broadleaf deciduous");
insert into tree_details_species values("Quercus myrsinifolia - bambooleaf oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus frainetto - Hungarian oak, Italian oak", "Broadleaf deciduous");
insert into tree_details_species values("Mespilus germanica - medlar", "Broadleaf deciduous");
insert into tree_details_species values("Chamaecyparis lawsoniana - Port Orford cedar", "Coniferous evergreen");
insert into tree_details_species values("Quercus macrocarpa - bur oak", "Broadleaf deciduous");
insert into tree_details_species values("Sassafras albidum - sassafras", "Broadleaf deciduous");
insert into tree_details_species values("Corylus avellana - hazel, filbert", "Broadleaf deciduous");
insert into tree_details_species values("Podocarpus macrophyllus - Buddhist pine", "Coniferous evergreen");
insert into tree_details_species values("Malus tschonoskii - Tschonoskii crabapple", "Broadleaf deciduous");
insert into tree_details_species values("Platanus occidentalis - American sycamore", "Broadleaf deciduous");
insert into tree_details_species values("Castanea sativa - Spanish chestnut", "Broadleaf deciduous");
insert into tree_details_species values("Prunus lusitanica - Portuguese laurel", "Broadleaf evergreen");
insert into tree_details_species values("Hamamelis spp. - witch hazel", "Broadleaf deciduous");
insert into tree_details_species values("Taxodium spp. - bald cypress", "Coniferous deciduous");
insert into tree_details_species values("Heptacodium miconioides - Seven-son plant", "Broadleaf deciduous");
insert into tree_details_species values("Acer miyabei - miyabe maple", "Broadleaf deciduous");
insert into tree_details_species values("Platycladus orientalis - Chinese arborvitae", "Coniferous evergreen");
insert into tree_details_species values("Quercus lobata - valley oak", "Broadleaf deciduous");
insert into tree_details_species values("Halesia spp. - silverbell", "Broadleaf deciduous");
insert into tree_details_species values("Betula papyrifera - paper birch", "Broadleaf deciduous");
insert into tree_details_species values("Cupressus sempervirens - Italian cypress", "Coniferous evergreen");
insert into tree_details_species values("Acer truncatum - Shandong or Shantung maple", "Broadleaf deciduous");
insert into tree_details_species values("Hovenia dulcis - Japanese raisin tree", "Broadleaf deciduous");
insert into tree_details_species values("Quercus imbricaria - shingle oak", "Broadleaf deciduous");
insert into tree_details_species values("Ziziphus jujuba - jujube", "Broadleaf deciduous");
insert into tree_details_species values("Aralia spp. - Aralia", "Broadleaf deciduous");
insert into tree_details_species values("Abies grandis - grand fir", "Coniferous evergreen");
insert into tree_details_species values("Quercus shumardii - Shumard oak", "Broadleaf deciduous");
insert into tree_details_species values("Rhus spp. - sumac", "Broadleaf deciduous");
insert into tree_details_species values("Chionanthus virginicus - white fringe tree", "Broadleaf deciduous");
insert into tree_details_species values("Eucryphia spp. - leatherwood", "Broadleaf evergreen");
insert into tree_details_species values("Stewartia monadelpha - orange-bark stewartia", "Broadleaf deciduous");
insert into tree_details_species values("Carya ovata - shagbark hickory", "Broadleaf deciduous");
insert into tree_details_species values("Quercus wislizeni - interior live oak", "Broadleaf evergreen");
insert into tree_details_species values("Picea pungens - Colorado blue spruce", "Coniferous evergreen");
insert into tree_details_species values("Hesperocyparis macrocarpa 'Goldcrest' - Lemon Cypress", "Coniferous evergreen");
insert into tree_details_species values("Acer pensylvanicum - Striped Maple", "Broadleaf deciduous");
insert into tree_details_species values("Carya spp. - hickories", "Broadleaf deciduous");
insert into tree_details_species values("Acer triflorum - three-flower maple", "Broadleaf deciduous");
insert into tree_details_species values("Corylus colurna - Turkish hazel", "Broadleaf deciduous");
insert into tree_details_species values("Quercus chrysolepis - canyon live oak", "Broadleaf evergreen");
insert into tree_details_species values("Davidia involucrata - dove tree", "Broadleaf deciduous");
insert into tree_details_species values("Lindera obtusiloba, Japanese spicebush", "Broadleaf deciduous");
insert into tree_details_species values("Thujopsis dolabrata - hiba arborvitae", "Coniferous evergreen");
insert into tree_details_species values("Populus alba - white poplar", "Broadleaf deciduous");
insert into tree_details_species values("Acer tataricum - Tatarian Maple", "Broadleaf deciduous");
insert into tree_details_species values("Poliothyrsis sinensis - pearlbloom tree", "Broadleaf deciduous");
insert into tree_details_species values("Nothofagus spp. - Southern beech", "Broadleaf deciduous");
insert into tree_details_species values("Ehretia dicksonii - Dickson ehretia", "Broadleaf deciduous");
insert into tree_details_species values("Pterocarya spp. - wingnut", "Broadleaf deciduous");
insert into tree_details_species values("Cunninghamia lanceolata - China fir", "Coniferous evergreen");
insert into tree_details_species values("Pteroceltis tatarinowii - winged hackberry", "Broadleaf deciduous");
insert into tree_details_species values("Acer davidii - snakebark maple", "Broadleaf deciduous");
insert into tree_details_species values("Hippophae rhamnoides - seaberry", "Broadleaf deciduous");
insert into tree_details_species values("Austrocedrus chilensis - Chilean cedar", "Coniferous evergreen");
insert into tree_details_species values("Tetradium daniellii syn. Evodia daniellii - Korean evodia, bee-bee tree", "Broadleaf deciduous");
insert into tree_details_species values("Acer mandshuricum - Manchurian maple", "Broadleaf deciduous");
insert into tree_details_species values("Zanthoxylum spp. - prickly ash", "Broadleaf deciduous");
insert into tree_details_species values("Taxus spp. - yew", "Coniferous evergreen");
insert into tree_details_species values("Quercus agrifolia - coast live oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus virginiana - southern live oak", "Broadleaf evergreen");
insert into tree_details_species values("Magnolia kobus - kobus or kobushi magnolia", "Broadleaf deciduous");
insert into tree_details_species values("Pinus sylvestris - Scots pine", "Coniferous evergreen");
insert into tree_details_species values("Stewartia pseudocamellia - Japanese stewartia", "Broadleaf deciduous");
insert into tree_details_species values("Firmiana simplex - Chinese parasol tree", "Broadleaf deciduous");
insert into tree_details_species values("Franklinia alatamaha - Franklin tree", "Broadleaf deciduous");
insert into tree_details_species values("Hesperocyparis arizonica - Arizona Cypress", "Coniferous evergreen");
insert into tree_details_species values("Picea sitchensis - Sitka spruce", "Coniferous evergreen");
insert into tree_details_species values("Quercus douglasii - blue oak", "Broadleaf deciduous");
insert into tree_details_species values("Cinnamomum camphora - camphor tree", "Broadleaf evergreen");
insert into tree_details_species values("Pseudolarix amabilis - golden larch", "Coniferous deciduous");
insert into tree_details_species values("Acer henryi - Henry maple", "Broadleaf deciduous");
insert into tree_details_species values("Sciadopitys verticillata - umbrella pine", "Coniferous evergreen");
insert into tree_details_species values("Feijoa sellowiana syn. Acca sellowiana - pineapple guava", "Broadleaf evergreen");
insert into tree_details_species values("Lyonothamnus floribunda ssp. asplenifolius - Catalina ironwood", "Broadleaf evergreen");
insert into tree_details_species values("Citrus trifoliata - Trifoliate Orange", "Broadleaf deciduous");
insert into tree_details_species values("Tamarix spp. - tamarisk, salt cedar", "Broadleaf deciduous");
insert into tree_details_species values("Picea glauca - white spruce", "Coniferous evergreen");
insert into tree_details_species values("Liquidambar formosana - Formosan sweetgum", "Broadleaf deciduous");
insert into tree_details_species values("Quercus emoryi - Emory oak", "Broadleaf evergreen");
insert into tree_details_species values("Melliodendron xylocarpum - melliodendron", "Broadleaf deciduous");
insert into tree_details_species values("Populus trichocarpa - black cottonwood", "Broadleaf deciduous");
insert into tree_details_species values("Castanopsis spp. - chinkapin", "Broadleaf evergreen");
insert into tree_details_species values("Abies procera - noble fir", "Coniferous evergreen");
insert into tree_details_species values("Toona sinensis syn. Cedrela sinensis - Chinese toon", "Broadleaf deciduous");
insert into tree_details_species values("Salix scouleriana - Scouler willow", "Broadleaf deciduous");
insert into tree_details_species values("Pyrus calleryana - flowering pear", "Broadleaf deciduous");
insert into tree_details_species values("Eleagnus angustifolia - Russian-olive", "Broadleaf deciduous");
insert into tree_details_species values("Pinus densiflora - Japanese red pine", "Coniferous evergreen");
insert into tree_details_species values("Pyrus pyrifolia - Asian pear", "Broadleaf deciduous");
insert into tree_details_species values("Pyrus communis - European pear", "Broadleaf deciduous");
insert into tree_details_species values("Tilia mongolica - Mongolian Linden", "Broadleaf deciduous");
insert into tree_details_species values("Betula utilis var. jacquemontii - Himalayan whitebarked birch, Jacquemont birch", "Broadleaf deciduous");
insert into tree_details_species values("Cedrus atlantica 'Glauca' - blue Atlas cedar", "Coniferous evergreen");
insert into tree_details_species values("Pinus jeffreyi - Jeffrey pine", "Coniferous evergreen");
insert into tree_details_species values("Ceanothus spp. - California lilac", "Broadleaf evergreen");
insert into tree_details_species values("Abies concolor - white fir", "Coniferous evergreen");
insert into tree_details_species values("Picea abies - Norway spruce", "Coniferous evergreen");
insert into tree_details_species values("Sorbus aria - whitebeam mountain ash", "Broadleaf deciduous");
insert into tree_details_species values("Prunus persica var. nucipersica - Nectarine", "Broadleaf deciduous");
insert into tree_details_species values("Abies pinsapo - Spanish fir", "Coniferous evergreen");
insert into tree_details_species values("Picea orientalis - Pontic spruce, Caucasian spruce, Oriental spruce", "Coniferous evergreen");
insert into tree_details_species values("Quercus mexicana - Mexican evergreen oak", "Broadleaf evergreen");
insert into tree_details_species values("Syringa reticulata ssp. pekinensis - Peking tree lilac", "Broadleaf deciduous");
insert into tree_details_species values("Hesperocyparis bakeri - Baker Cypress", "Coniferous evergreen");
insert into tree_details_species values("Chrysolepis chrysophylla - Golden Chinkapin", "Broadleaf evergreen");
insert into tree_details_species values("Magnolia laevifolia - Magnolia laevifolia", "Broadleaf evergreen");
insert into tree_details_species values("Chilopsis linearis - desert willow", "Broadleaf deciduous");
insert into tree_details_species values("Acer japonicum - full-moon maple, Japanese maple", "Broadleaf deciduous");
insert into tree_details_species values("Quercus alba - eastern white oak", "Broadleaf deciduous");
insert into tree_details_species values("Genista aetnensis - Mt. Aetna broom", "Broadleaf deciduous");
insert into tree_details_species values("Quercus stellata - post oak", "Broadleaf deciduous");
insert into tree_details_species values("Frangula alnus 'Asplenifolia' - asplenifolia alder buckthorn", "Broadleaf deciduous");
insert into tree_details_species values("Quercus dentata - emperor or Daimyo oak", "Broadleaf deciduous");
insert into tree_details_species values("Cladrastis sinensis 'China Rose' - Chinese yellowwood", "Broadleaf deciduous");
insert into tree_details_species values("Osmanthus fragrans - fragrant olive", "Broadleaf evergreen");
insert into tree_details_species values("Koelreuteria bipinnata - Chinese Flame Tree", "Broadleaf deciduous");
insert into tree_details_species values("Torreya californica - California nutmeg", "Coniferous evergreen");
insert into tree_details_species values("Viburnum cylindricum - tubeflower viburnum", "Broadleaf evergreen");
insert into tree_details_species values("Pinus flexilis - limber pine", "Coniferous evergreen");
insert into tree_details_species values("Fremontodendron californicum - California Fremontia", "Broadleaf evergreen");
insert into tree_details_species values("Cinnamomum japonicum - Japanese Cinnamon", "Broadleaf evergreen");
insert into tree_details_species values("Pinus parviflora - Japanese white pine", "Coniferous evergreen");
insert into tree_details_species values("Alnus rubra - red alder", "Broadleaf deciduous");
insert into tree_details_species values("Prunus mume - Japanese apricot", "Broadleaf deciduous");
insert into tree_details_species values("xGordlinia grandiflora - mountain gordlinia", "Broadleaf evergreen");
insert into tree_details_species values("Arbutus Arizonica - Arizona Madrone", "Broadleaf evergreen");
insert into tree_details_species values("Castanopsis cuspidata - Japanese Chinquapin", "Broadleaf evergreen");
insert into tree_details_species values("Quercus greggii - Gregg oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus sartorii - encino blanco, Sartor's oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus gravesii - Chisos Red Oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus canbyi - Sierra oak, Canby oak", "Broadleaf deciduous");
insert into tree_details_species values("Quercus x comptoniae - Compton oak", "Broadleaf deciduous");
insert into tree_details_species values("Quercus nigra - water oak", "Broadleaf deciduous");
insert into tree_details_species values("Magnolia macrophylla - Bigleaf Magnolia", "Broadleaf deciduous");
insert into tree_details_species values("Nyssa sinensis - Chinese tupelo", "Broadleaf deciduous");
insert into tree_details_species values("Prumnopitys andina - plum-fruited yew, lleuque, Andean podocarp", "Coniferous evergreen");
insert into tree_details_species values("Hesperocyparis abramsiana - Santa Cruz Cypress", "Coniferous evergreen");
insert into tree_details_species values("Sapindus drummondii syn. Sapindus saponaria var. drummondii - western soapberry", "Broadleaf deciduous");
insert into tree_details_species values("Athrotaxis x laxifolia - summit cedar", "Coniferous evergreen");
insert into tree_details_species values("Xanthocyparis vietnamensis - Golden Vietnamese Cypress", "Coniferous evergreen");
insert into tree_details_species values("Quercus tomentella - island oak", "Broadleaf evergreen");
insert into tree_details_species values("Maackia chinensis- Chinese Maackia", "Broadleaf deciduous");
insert into tree_details_species values("Podocarpus chingianus - Japanese Yew", "Coniferous evergreen");
insert into tree_details_species values("Quercus polymorpha - Monterrey oak, Mexican white oak", "Broadleaf evergreen");
insert into tree_details_species values("Viburnum odoratissimum var. awabuki - Sweet Viburnum", "Broadleaf evergreen");
insert into tree_details_species values("Abies koreana - Korean fir", "Coniferous evergreen");
insert into tree_details_species values("Hesperocyparis macnabiana - McNab Cypress", "Coniferous evergreen");
insert into tree_details_species values("Acer rufinerve - redvein maple", "Broadleaf deciduous");
insert into tree_details_species values("Pistacia vera - Pistachio", "Broadleaf deciduous");
insert into tree_details_species values("Quercus gambellii - Gambel oak", "Broadleaf deciduous");
insert into tree_details_species values("Styrax americanus - American Snowbell", "Broadleaf deciduous");
insert into tree_details_species values("Osmanthus x fortunei - Fortune's Osmanthus", "Broadleaf evergreen");
insert into tree_details_species values("Leptospermum spp.  - Tea tree", "Broadleaf evergreen");
insert into tree_details_species values("Quercus muehlenbergii - chinkapin oak", "Broadleaf deciduous");
insert into tree_details_species values("Lithocarpus densiflorus - tanoak or tanbark oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus engelmanii - Engelmann oak", "Broadleaf deciduous");
insert into tree_details_species values("Quercus oblongifolia - Mexican blue oak, Sonoran blue oak", "Broadleaf evergreen");
insert into tree_details_species values("Quercus kelloggii - California black oak", "Broadleaf deciduous");
